site_name: Grinder-Coveralls
site_description: Grinder plug-in collecting your code coverage as LCOV and uploading it to the Coveralls service.
site_author: Cédric Belin - cedric@belin.io
site_url: https://dev.belin.io/grinder-coveralls

docs_dir: .
site_dir: ../web

repo_name: GitHub
repo_url: https://github.com/cedx/grinder-coveralls
edit_uri: ''

copyright: Copyright &copy; 2019 - 2020 Cédric Belin
google_analytics:
  - !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
  - auto

extra:
  social:
    - {type: globe, link: 'https://belin.io'}
    - {type: github, link: 'https://github.com/cedx'}
    - {type: twitter, link: 'https://twitter.com/cedxbelin'}
    - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md
      - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: blue, accent: blue}
